### ISSUE TITLE
error while compiling esp cam component

### ISSUE THREAD

**Issue by cyrok** [MichaKersloot/esphome_custom_components#1]
i struggle while compiling. i checked multiple times but cant figure out, what im doing wrong.
here my yaml and the output log.

```
# Basic configuration for an ESP32 device
esphome:
 name: cam1
 friendly_name: Kamera Küchenfenster

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
    components: [ esp32_camera ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  - platform: esphome
    password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cam1 Fallback Hotspot"
    password: "XXX"

esp32_camera_web_server:
  - port: 21001
    mode: stream
  - port: 21011
    mode: snapshot

esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 15MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  resolution: 2560x1920
  jpeg_quality: 10
  name: cam1
```

```
INFO ESPHome 2025.6.0
INFO Reading configuration /config/cam.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Updating https://github.com/espressif/esp32-camera.git@v2.0.15
INFO Compiling app...
Processing cam (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530 
 - toolchain-xtensa-esp-elf @ 13.2.0+20240530
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/cam/src/esphome/components/esp32_camera/esp32_camera.cpp.o
Archiving .pioenvs/cam/esp-idf/esp_http_client/libesp_http_client.a
Compiling .pioenvs/cam/esp_http_server/src/httpd_parse.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_sess.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_txrx.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_uri.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_ws.c.o
Compiling .pioenvs/cam/esp_http_server/src/util/ctrl_sock.c.o
Compiling .pioenvs/cam/esp_https_ota/src/esp_https_ota.c.o
Compiling .pioenvs/cam/esp_https_server/src/https_server.c.o
Compiling .pioenvs/cam/esp_hw_support/cpu.c.o
Compiling .pioenvs/cam/esp_hw_support/port/esp32s3/esp_cpu_intr.c.o
Compiling .pioenvs/cam/esp_hw_support/esp_memory_utils.c.o
Compiling .pioenvs/cam/esp_hw_support/port/esp32s3/cpu_region_protect.c.o
In file included from src/esphome/components/esp32_camera/esp32_camera.cpp:4:
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:51:52: error: 'class esphome::esp32_camera::ESP32Camera' has no member named 'internal_'; did you mean 'is_internal'?
   51 |   ESP_LOGCONFIG(TAG, "  Internal: %s", YESNO(this->internal_));
      |                                                    ^~~~~~~~~
src/esphome/core/log.h:101:101: note: in definition of macro 'esph_log_config'
  101 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:51:3: note: in expansion of macro 'ESP_LOGCONFIG'
   51 |   ESP_LOGCONFIG(TAG, "  Internal: %s", YESNO(this->internal_));
      |   ^~~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:51:40: note: in expansion of macro 'YESNO'
   51 |   ESP_LOGCONFIG(TAG, "  Internal: %s", YESNO(this->internal_));
      |                                        ^~~~~
Compiling .pioenvs/cam/esp_hw_support/esp_clk.c.o
Compiling .pioenvs/cam/esp_hw_support/clk_ctrl_os.c.o
Archiving .pioenvs/cam/esp-idf/esp_http_server/libesp_http_server.a
Compiling .pioenvs/cam/esp_hw_support/hw_random.c.o
Compiling .pioenvs/cam/esp_hw_support/intr_alloc.c.o
Archiving .pioenvs/cam/esp-idf/esp_https_server/libesp_https_server.a
Compiling .pioenvs/cam/esp_hw_support/mac_addr.c.o
Compiling .pioenvs/cam/esp_hw_support/periph_ctrl.c.o
Archiving .pioenvs/cam/esp-idf/esp_https_ota/libesp_https_ota.a
Compiling .pioenvs/cam/esp_hw_support/revision.c.o
Compiling .pioenvs/cam/esp_hw_support/rtc_module.c.o
*** [.pioenvs/cam/src/esphome/components/esp32_camera/esp32_camera.cpp.o] Error 1
========================== [FAILED] Took 2.86 seconds ==========================
```

**Comment by MichaKersloot** [comment]
As I'm not testing on the esp-idf framework. You could try to alter:

```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf`
``` 
to
```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
```

**Comment by cyrok** [comment]
the error now looks diferent, but still the same issue with the "internal"

![Image](https://github.com/user-attachments/assets/b4ea27b6-c239-4b36-9c84-b67e394c56fd)

**Comment by cyrok** [comment]
mby the error is because esphome is already on 6.0? does it work for you? i try to compile trough the webpage, not localy, does this anything diferent?

**Comment by cyrok** [comment]
another addition: without your git package will it work, so something in your git seems to be the problem. but with the standard package i get a connection and all, but it seems something is a miss, while using the ov5640, because single frames are reported broken over the browser (cant view "cause corrupted file) nor do i get a stream.

but i can tell, that switching to the arduino environment helped with another issue, that made the esp run pretty bad and crashed it all the time.

i thing you can tell me more why i wont get a picture?

**Comment by MichaKersloot** [comment]
Hi,

I'm not updated to 2025.6 yet. I did need to update my patch for version 2025.5, so maybe it won't compile on .6 yet. My 'patch' is super simple. I only change one line in esp32_camera.cpp:

`this->config_.fb_location = CAMERA_FB_IN_PSRAM;`
becomes
`this->config_.fb_location = CAMERA_FB_IN_DRAM;`

In your config you also enabled the web_server on port 21001 and 21011. Are you getting some picture on one of these ports?

Another one is you can try to view the source of your broken image. It could contain information that tells you more about the error.

**Comment by MichaKersloot** [comment]
Ok, I've put some (more than I expected) time in understanding git and esphome and was able to create a new repository and made  the option configurable for version 2025.06. Could you please check this out:

```
external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome
      ref: v2025_06
    components: [esp32_camera]
    refresh: 10min
```

and for the device:
```
esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 15MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  resolution: 2560x1920
  jpeg_quality: 10
  name: cam1
  frame_buffer_dram: true
```

**Comment by cyrok** [comment]
so far now the video server and the cam part failes
i attached the log

[logs_cam_run.txt](https://github.com/user-attachments/files/20846299/logs_cam_run.txt)

**Comment by Grey-Lancaster** [comment]
This works.  It requires `frame_buffer_dram: true` or the website fails to start.
`refresh: 10min`
gives a build error

```
external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome
      ref: v2025_06
    components: [ esp32_camera ]
    # refresh: 10min
esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 10MHz  #chanegd from 20 mhz to 12
  i2c_pins:
    sda: GPIO4 # was 4
    scl: GPIO5    # was 5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  
  vsync_pin: GPIO6 # was 6
  href_pin: GPIO7  #was 7
  pixel_clock_pin: GPIO13 # was 13
  jpeg_quality: 10
  frame_buffer_dram: true
  #power_down_pin: GPIO33
  # Image settings
  name: ESP32 Camera

  vertical_flip: False
  horizontal_mirror: False

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
```
