### ISSUE TITLE
error with esphome 2025.6

### ISSUE THREAD

**Issue by Grey-Lancaster** [MichaKersloot/esphome_custom_components#3]
I get a build error

```
external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
    components: [ esp32_camera ]
esp32_camera:
```

```
Compiling .pioenvs/esphome-web-226cf0/src/esphome/components/mdns/mdns_component.cpp.o
In file included from src/esphome/components/esp32_camera/esp32_camera.cpp:4:
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:50:52: error: 'class esphome::esp32_camera::ESP32Camera' has no member named 'internal_'; did you mean 'is_internal'?
```
And this does not work:

```
external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome/tree/v2025_06
    components: [ esp32_camera ]
esp32_camera:
```
